[workspace]

[package]
name = "gen-stubs"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1"
pyo3-introspection = { git = "https://github.com/Tpt/pyo3.git", branch = "tpt/stub-doc" }
